[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "bash -lc \"shopt -s extglob; if [ -d .next ]; then rm -rf .next/!(cache); fi\"",
  "npm run build"
]

[start]
cmd = "npm run start"
